
tasks:
  - name: Compile
    init: gp sync-await setup-node
    command: nvm use && yarn run compile && exit 0
  - name: Setup node
    init: |
      nvm install && \
      nvm use && \
      yarn install --frozen-lockfile && \
      gp sync-done setup-node && \
      exit 0
  - name: Setup slither
    init: |
      sudo apt-get update && \
      sudo apt-get install -y python3-pip && \
      pip3 install slither-analyzer && \
      rm -f ./slither.json ./slither_badge.json && \
      exit 0